/*
 * Reserved memory (FIXME: Throw this shit away!)
 */

#if 0
#define	PHYS_SIZE			(SZ_128M + SZ_64M + SZ_16M)

#define DRAM_END_ADDR 			(PHYS_OFFSET + PHYS_SIZE)
#define RESERVED_PMEM_END_ADDR 		(DRAM_END_ADDR)

#define RESERVED_MEM_CMM		(SZ_2M + SZ_1M)
#define RESERVED_MEM_MFC		(SZ_4M + SZ_2M)
/* PMEM_PIC and MFC use share area */
#define RESERVED_PMEM_PICTURE		(SZ_4M + SZ_2M)
#define RESERVED_PMEM_JPEG		(SZ_2M + SZ_1M)
#define RESERVED_PMEM_PREVIEW		(SZ_2M)
#define RESERVED_PMEM_RENDER	  	(SZ_2M)
#define RESERVED_PMEM_STREAM	  	(SZ_2M)
/* G3D is shared with uppper memory areas */
#define RAM_CONSOLE_SIZE		(SZ_2M)
#define RESERVED_G3D			(SZ_16M + SZ_8M + SZ_4M + SZ_2M)
#define RESERVED_PMEM_GPU1		(RESERVED_G3D)
#define RESERVED_PMEM			(SZ_8M)

#define CMM_RESERVED_MEM_START		(RESERVED_PMEM_END_ADDR \
					- RESERVED_MEM_CMM)
#define MFC_RESERVED_MEM_START		(CMM_RESERVED_MEM_START \
					- RESERVED_MEM_MFC)
#define PICTURE_RESERVED_PMEM_START	(MFC_RESERVED_MEM_START)
#define JPEG_RESERVED_PMEM_START	(MFC_RESERVED_MEM_START \
					- RESERVED_PMEM_JPEG)
#define PREVIEW_RESERVED_PMEM_START	(JPEG_RESERVED_PMEM_START \
					- RESERVED_PMEM_PREVIEW)
#define RENDER_RESERVED_PMEM_START	(PREVIEW_RESERVED_PMEM_START \
					- RESERVED_PMEM_RENDER)
#define STREAM_RESERVED_PMEM_START	(RENDER_RESERVED_PMEM_START \
					- RESERVED_PMEM_STREAM)
/* G3D is shared with uppper memory areas */
#define RAM_CONSOLE_START		(RESERVED_PMEM_END_ADDR \
					- RAM_CONSOLE_SIZE)
#define G3D_RESERVED_START		(RAM_CONSOLE_START \
					- RESERVED_G3D)
#define GPU1_RESERVED_PMEM_START	(G3D_RESERVED_START)
#define RESERVED_PMEM_START		(GPU1_RESERVED_PMEM_START \
					- RESERVED_PMEM)
#define PHYS_UNRESERVED_SIZE		(RESERVED_PMEM_START - PHYS_OFFSET)

#else

#define	PHYS_SIZE			(SZ_128M + SZ_64M + SZ_16M)

#define DRAM_END_ADDR 			(PHYS_OFFSET + PHYS_SIZE)
#define RESERVED_PMEM_END_ADDR 		(DRAM_END_ADDR)

#define RAM_CONSOLE_SIZE		(SZ_2M)
#define RESERVED_PMEM_GPU1		(SZ_16M + SZ_8M + SZ_4M + SZ_2M)
#define RESERVED_PMEM			(SZ_16M)

#define RAM_CONSOLE_START		(RESERVED_PMEM_END_ADDR \
					- RAM_CONSOLE_SIZE)
#define GPU1_RESERVED_PMEM_START	(RAM_CONSOLE_START \
					- RESERVED_PMEM_GPU1)
#define RESERVED_PMEM_START		(GPU1_RESERVED_PMEM_START \
					- RESERVED_PMEM)
#define PHYS_UNRESERVED_SIZE		(RESERVED_PMEM_START - PHYS_OFFSET)

#endif
